
services:
  walletapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: walletapp
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wallet-db:5432/wallet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1923
      - SPRING_LIQUIBASE_ENABLED=true
    depends_on:
      wallet-db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  wallet-db:
    image: 'postgres:latest'
    container_name: wallet-db
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_PASSWORD=1923
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  postgres_data: